### PR TITLE
Hotfix/go docs #none

### PR DESCRIPTION
**Pull request by blankdots**
I broke gh-pages docs with PR #373 and this aims to fix it and make it more manageable 

new built page is available at: [neicnordic.github.io/sda-pipeline/](https://neicnordic.github.io/sda-pipeline/)

**I apologise for breaking them, but it was very confusing how to test them.**

### CODE REVIEW

**Comment by kjellp** [comment]
Not sure if this is part of what was boken : clicking broker link in doc page first and then getMessages link, it seems to be a broken link to the corresponding source code location (using localhost instead of github location).

**Review by jbygdell — APPROVED** [review]

**Comment by blankdots** [comment]
> Not sure if this is part of what was boken : clicking broker link in doc page first and then getMessages link, it seems to be a broken link to the corresponding source code location (using localhost instead of github location).
> 
> Same for other functions. Fix now , or accept PR and make new issue for this sub - bug ?

I will try to fix them as part of this PR

**Comment by blankdots** [comment]
@kjellp now it should resolve. I hope i fixed them all.

**Comment by kjellp** [comment]
@blankdots jepp I tried to randomly test 10-20 links, and they all resolved.

**Review by kjellp — APPROVED** [review]
LGTM

**Review by aaperis — APPROVED** [review]

**Pull request merged**
