### PR TITLE
Add minimal testing suite for sync

### PR DESCRIPTION
**Pull request by jbygdell**

### CODE REVIEW

**Comment by pontus** [comment]
Perhaps we can add an assert to verify that it populates the Backup configuration properly?

**Review by pontus — APPROVED** [review]
Not much to do in testing in `cmd` until we refactor.

**Comment by jbygdell** [comment]
> Not much to do in testing in `cmd` until we refactor.

Precisely, noting in `main()` can be verified as it is now.

**Review by blankdots — APPROVED** [review]

**Comment by blankdots** [comment]
curious what refactor plans you have ...

**Pull request merged**
