### PR TITLE
Handle channel closures

### LINKED ISSUE #412: Fix MQ connectivity
If the connection to the MQ stalls, it will not be repoened unless the process is restarted.
relevant error mesage: `reason: Exception (504) Reason: \"channel/connection is not open\")"`

A/C: 
- [ ] create testcase for MQ reconnects
- [ ] check MQ connection before sending a message and reconnect if needed.

### PR DESCRIPTION
**Pull request by jbygdell**
These seems to be the smallest changed needed in order to be able to handle a closed channel.

Using the library version of the Channel definition `*amqp.Channel` will require a much larger rewrite, specially of our tests.

Testing this is not straight forward as a channel can only be closed form the client side with the exemption of a channel time out event that happens after 30 min of inactivity.
To force a channel closure these actions needs to be taken:
* start MQ, DB and finalize
* pause the DB
* send a correct message to finalize
* wait for 30 min

closes #412

### CODE REVIEW

**Comment by pontus** [comment]
Looks ok - a few general comments:

* Given that it's a failure if we exit, it would be nice to signal that, so a leading `defer func() { os.Exit(1) }()` would be nice
* As we're exiting the loop and have defers for closing, is there any benefit of closing the `db` on connection failure?
* I have a slight preference for exiting the loop directly on channel failure rather than closing the connection and waiting for that to be detected -  I guess either should work, though.

**Review by pontus — APPROVED** [review]

**Review by blankdots — APPROVED** [review]

**Review by blankdots — COMMENTED** [review]
after this maybe we also need to rebase #517 ?

**Comment by jbygdell** [comment]
> Looks ok - a few general comments:
> 
> * Given that it's a failure if we exit, it would be nice to signal that, so a leading `defer func() { os.Exit(1) }()` would be nice

It's not really an error, we just can't do a reconnect without restarting the main work loop.


> * As we're exiting the loop and have defers for closing, is there any benefit of closing the `db` on connection failure?
> * I have a slight preference for exiting the loop directly on channel failure rather than closing the connection and waiting for that to be detected -  I guess either should work, though.

**Comment by jbygdell** [comment]
Let's see if this can be made somewhat cleaner, I found a way to reduce the timeout to be more manageable.

**Comment by pontus** [comment]
I'd say seeing anything closed would imply an error (being why we normally loop forever), but I wouldn't have approved if I couldn't live with it, and don't really believe it matters.

**Review by blankdots — APPROVED** [review]

**Review by pontus — APPROVED** [review]

**Review by aaperis — APPROVED** [review]
looks good to me

**Pull request merged**
