### PR TITLE
Refactor/repo cleanup

### PR DESCRIPTION
**Pull request by blankdots**
- [x] fix typos in the code and docs
- [x] remove docker hub hooks
- [x] adjust documentation to make it somewhat more understandable

Question: do we active `deepsource` ? we might need to fix issues if we do

This will go as `patch` version update as we made some code changes.

### CODE REVIEW

**Review by jbygdell — APPROVED** [review]

**Comment by jbygdell** [comment]
DB image has changed, use v1.3.1 instead of latest in the tests until next version of the helm chart is released.

**Comment by blankdots** [comment]
we might need to bring https://github.com/neicnordic/sda-db/pull/19/files#diff-6f9d41d046756f0ddc2fcee0626bdb50100d12b88f293734eff742818e03efa2L92-L97 back to make db work with tls unless we want to chown the certs ourselves :thinking:

**Review by norling — APPROVED** [review]
Is `dev_utils/make_certs.sh` supposed to be empty? :) otherwise - looks good!

**Comment by blankdots** [comment]
> Is `dev_utils/make_certs.sh` supposed to be empty? :) otherwise - looks good!

I changed permissions on that it (chmod +x), it still has content https://github.com/neicnordic/sda-pipeline/blob/refactor/repo-cleanup/dev_utils/make_certs.sh

**Review by dbampalikis — APPROVED** [review]

**Review by jbygdell — APPROVED** [review]

**Pull request merged**
