### PR TITLE
[backup] make use of header re-encrypt

### PR DESCRIPTION
**Pull request by blankdots**
- crypt4gh package as of 1.6.0 has header and file re-encrypt functionality. - related PR: https://github.com/neicnordic/crypt4gh/pull/42

Not sure I see anything in the integration tests that the file and/or the header were re-encrypted ok, do we have something like this?

### CODE REVIEW

**Comment by dbampalikis** [comment]
> 

Maybe I am off, but wouldn't [this](https://github.com/neicnordic/sda-pipeline/blob/6c23836fe8500d48237a99bb826dcf88ef03c0cb/.github/integration/tests/s3header/50_check_files.sh#L68) check that the file was actually correctly encrypted and decrypted with the new key?

**Review by norling — APPROVED** [review]
Code looks really neat! :)

**Review by dbampalikis — APPROVED** [review]
Looks good and reduces the code used for that by a lot!

**Comment by blankdots** [comment]
> Maybe I am off, but wouldn't [this](https://github.com/neicnordic/sda-pipeline/blob/6c23836fe8500d48237a99bb826dcf88ef03c0cb/.github/integration/tests/s3header/50_check_files.sh#L68) check that the file was actually correctly encrypted and decrypted with the new key?

awesome, did not catch that. thx!

**Review by aaperis — APPROVED** [review]
looks nice :)

**Pull request merged**
